import type { Artifact, Run } from "../framework-data";
import { publicPath } from "../framework-data";
import { StepViewer } from "./step-viewer";

const roleLabels: Record<Artifact["role"], string> = {
  "cad-source": "Editable CAD source",
  step: "STEP exchange model",
  drawing: "Drawing",
  bom: "Bill of materials",
  calculation: "Calculation",
  supporting: "Supporting file",
};

function ArtifactList({ artifacts, basePath }: { artifacts: Artifact[]; basePath: string }) {
  if (artifacts.length === 0) return <p className="empty-copy">No publishable static artifacts were admitted for this run.</p>;
  return <ul className="artifact-list">{artifacts.map((artifact) => <li key={artifact.id}><div><strong>{artifact.label ?? artifact.id}</strong><span>{roleLabels[artifact.role]} · {artifact.path}</span><code>SHA-256 {artifact.sha256}</code></div><a className="button-link" href={publicPath(basePath, artifact.download)} download={artifact.downloadName}>DOWNLOAD</a></li>)}</ul>;
}

function ProcessEvidence({ run, basePath }: { run: Run; basePath: string }) {
  if (!run.processEvidence) {
    return <p className="empty-copy">The portable publication deliberately excludes private evaluator state and candidate process-record paths.</p>;
  }
  return <><p>The initial plan is preserved separately from the later decision and verification record.</p><ul className="artifact-list"><li><div><strong>Initial requirements and plan</strong><span>{run.processEvidence.initialPlan.path}</span><code>SHA-256 {run.processEvidence.initialPlan.sha256}</code></div><a className="button-link" href={publicPath(basePath, run.processEvidence.initialPlan.download)} download={run.processEvidence.initialPlan.downloadName}>DOWNLOAD</a></li><li><div><strong>Alternatives, decisions, revisions, and verification</strong><span>{run.processEvidence.workRecord.path}</span><code>SHA-256 {run.processEvidence.workRecord.sha256}</code></div><a className="button-link" href={publicPath(basePath, run.processEvidence.workRecord.download)} download={run.processEvidence.workRecord.downloadName}>DOWNLOAD</a></li></ul></>;
}

export function RunDetail({ run, basePath }: { run: Run; basePath: string }) {
  const stepArtifacts = run.artifacts.filter((artifact) => artifact.role === "step");
  const byRole = (role: Artifact["role"]) => run.artifacts.filter((artifact) => artifact.role === role);
  const validation = run.validation;
  const evaluation = run.evaluation?.summary;
  return <main className="detail-page">
    <section className="detail-hero"><p className="eyebrow">RUN / {run.id}</p><h1>{run.id}</h1><p>{run.summary ?? "A submitted engineering design benchmark run."}</p><dl className="metadata-grid"><div><dt>Benchmark</dt><dd><a href={`${basePath}/benchmarks/${run.benchmarkId}/`}>{run.benchmarkId} / {run.benchmarkVersion}</a></dd></div><div><dt>Run status</dt><dd>{run.status}</dd></div><div><dt>Submitted</dt><dd>{new Date(run.submittedAt).toISOString()}</dd></div><div><dt>Model</dt><dd>{run.model ? [run.model.provider, run.model.name, run.model.version].join(" / ") : "Disclosed only at the post-review cohort level"}</dd></div></dl></section>
    <nav className="section-nav" aria-label="Run sections"><a href="#overview">OVERVIEW</a><a href="#process">PROCESS</a><a href="#model">3D</a><a href="#drawing">DRAWING</a><a href="#bom">BOM</a><a href="#calculation">CALCULATION</a><a href="#files">FILES</a><a href="#evaluation">EVALUATION</a><a href="#validation">VALIDATION</a></nav>
    <section id="overview" className="content-section"><h2>Overview</h2><p>This neutral shell exposes admitted static evidence without embedding candidate-supplied HTML, scripts, or styling.</p><dl className="metadata-grid"><div><dt>Launch</dt><dd>{run.launchId}</dd></div><div><dt>Cohort</dt><dd>{run.cohortId}</dd></div><div><dt>Task packet digest</dt><dd><code>{run.taskPacketDigest}</code></dd></div><div><dt>Fairness fingerprint</dt><dd><code>{run.fairnessFingerprint}</code></dd></div><div><dt>Bundle seal</dt><dd><code>{run.seal.bundleSha256}</code></dd></div><div><dt>Seal algorithm</dt><dd>{run.seal.algorithm}</dd></div></dl></section>
    <section id="process" className="content-section"><h2>Design process evidence</h2><ProcessEvidence run={run} basePath={basePath} />{run.process ? <div className="process-grid"><article><h3>Requirements</h3><ul>{run.process.plan.requirements.map((item) => <li key={item.id}><strong>{item.id}</strong><span>{item.statement}</span><small>{item.source}</small></li>)}</ul></article><article><h3>Planned alternatives</h3><ul>{run.process.plan.alternativesToEvaluate.map((item) => <li key={item.id}><strong>{item.id}</strong><span>{item.question}</span><small>{item.requirementRefs.join(", ")}</small></li>)}</ul></article><article><h3>Decisions</h3><ul>{run.process.workRecord.decisions.map((item) => <li key={item.id}><strong>{item.id} · {item.choice}</strong><span>{item.rationale}</span><small>{item.tradeoffs}</small></li>)}</ul></article><article><h3>Verification</h3><ul>{run.process.workRecord.verificationClaims.map((item) => <li key={item.id}><strong>{item.id} · {item.result}</strong><span>{item.method}</span><small>{item.requirementRefs.join(", ")}</small></li>)}</ul></article></div> : null}</section>
    <section id="model" className="content-section"><h2>3D</h2>{stepArtifacts.length === 0 ? <p className="empty-copy">No STEP artifact was admitted.</p> : stepArtifacts.map((artifact) => artifact.viewer?.status === "ready" ? <StepViewer key={artifact.id} label={artifact.label ?? artifact.id} meshUrl={publicPath(basePath, artifact.viewer.mesh)} /> : <div className="notice" key={artifact.id}><strong>3D display unavailable</strong><p>{artifact.viewer?.message ?? "STEP preprocessing did not produce a viewer asset."}</p><a href={publicPath(basePath, artifact.download)} download={artifact.downloadName}>Download original STEP</a></div>)}</section>
    <section id="drawing" className="content-section"><h2>Drawing</h2><ArtifactList artifacts={byRole("drawing")} basePath={basePath} /></section>
    <section id="bom" className="content-section"><h2>Bill of materials</h2><ArtifactList artifacts={byRole("bom")} basePath={basePath} /></section>
    <section id="calculation" className="content-section"><h2>Calculation</h2><ArtifactList artifacts={byRole("calculation")} basePath={basePath} /></section>
    <section id="files" className="content-section"><h2>Files</h2><ArtifactList artifacts={run.artifacts} basePath={basePath} /></section>
    <section id="evaluation" className="content-section"><h2>Evaluator assessment</h2>{!evaluation ? <p className="empty-copy">No finalized evaluator summary is public for this run.</p> : <><p className={`status status-${evaluation.status}`}>{evaluation.status.toUpperCase()}</p><dl className="metadata-grid"><div><dt>Baseline qualification</dt><dd>{String(evaluation.qualification?.baselineQualified ?? "not evaluated")}</dd></div><div><dt>Change qualification</dt><dd>{String(evaluation.qualification?.changeQualified ?? "not evaluated")}</dd></div><div><dt>Highest checkpoint</dt><dd>{evaluation.attainment?.highestVerifiedCheckpoint ?? "not recorded"}</dd></div><div><dt>Evaluator record digest</dt><dd><code>{evaluation.evaluationRecordSha256}</code></dd></div></dl>{evaluation.gates?.length ? <><h3>Gate outcomes</h3><ul className="check-list">{evaluation.gates.map((gate) => <li key={gate.id}><strong>{gate.id}</strong><span>{gate.label ?? "Gate"}: {gate.result}</span></li>)}</ul></> : null}{evaluation.dimensions?.length ? <><h3>D01–D10 vector</h3><table className="comparison"><thead><tr><th>Dimension</th><th>Score</th><th>Observed interval</th></tr></thead><tbody>{evaluation.dimensions.map((dimension) => <tr key={dimension.id}><td>{dimension.id} {dimension.label ?? ""}</td><td>{dimension.score ?? "not evaluable"}</td><td>{dimension.scoreInterval?.join("–") ?? "—"}</td></tr>)}</tbody></table></> : null}<p>This evidence reports ordinal dimensions, gates, raw metrics, and efficiency separately. No composite score, rank, or winner is published.</p>{run.evaluation?.download ? <a className="button-link" href={publicPath(basePath, run.evaluation.download)} download>DOWNLOAD PUBLIC EVALUATION SUMMARY</a> : null}</>}</section>
    <section id="validation" className="content-section"><h2>Validation</h2>{!validation ? <p className="empty-copy">No validation summary is available yet.</p> : <><p className={`status status-${validation.status}`}>{validation.status.toUpperCase()}</p>{validation.checks.length ? <ul className="check-list">{validation.checks.map((item, index) => <li key={`${item.name}-${index}`}><strong className={`check-${item.status}`}>{item.status.toUpperCase()}</strong><span>{item.name}{item.detail ? ` · ${item.detail}` : ""}</span></li>)}</ul> : null}{validation.issues.length > 0 ? <ul className="issue-list">{validation.issues.map((item) => <li key={`${item.code}-${item.path ?? ""}`}><code>{item.code}</code> {item.message}</li>)}</ul> : <p className="empty-copy">No public validation issues were reported.</p>}</>}</section>
  </main>;
}
